etl:
  raw_data_dir: RAWDATA/RAWDATA.csv
  table_name: customer_data

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  ingested_dir: artifacts/data_ingestion/ingested
  table_name: customer_data

data_validation:
  root_dir: artifacts/data_validation
  train_dir: artifacts/data_ingestion/train.csv
  test_dir: artifacts/data_ingestion/test.csv
  status_dir: artifacts/data_validation/status.json

data_transformation:
  root_dir: artifacts/data_transformation
  train_dir: artifacts/data_ingestion/train.csv
  test_dir: artifacts/data_ingestion/test.csv
  preprocessor_dir: artifacts/data_transformation/preprocessor.joblib

lr_model_training:
  root_dir: artifacts/lr_model_training
  model_dir: artifacts/lr_model_training/lr_model.joblib
  X_train_dir: artifacts/data_transformation/X_train.npz
  y_train_dir: artifacts/data_transformation/y_train.csv
