LogisticRegression:
  solver: saga
  max_iter: 1000
  class_weight: balanced
  C: 1

GradientBoostingClassifier:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3
  random_state: 42

SGDClassifier:
  loss: hinge
  penalty: l2
  max_iter: 500
